yiisoft/yii-debug-api

CHANGELOG.md
src/Controller/DebugController.php
src/Repository/CollectorRepository.php

| Tests pass?   | ✔️
| Fixed issues  | #6

Fixed view debug info by id

---

src/Controller/DebugController.php
src/Provider/DebugApiProvider.php
src/Repository/CollectorRepository.php

Adjustments

---

.scrutinizer.yml
src/Controller/DebugController.php
src/Provider/DebugApiProvider.php
src/Repository/CollectorRepository.php
src/Repository/CollectorRepositoryInterface.php

Add object view

---

src/Repository/CollectorRepository.php

| Breaks BC?    | ✔️
| Tests pass?   | ✔️
| Depends on  | https://github.com/yiisoft/yii-debug/pull/61
:warning:  Before merge need to check in real integration

Fix files finding

---

src/Provider/DebugApiProvider.php

Fix api provider

---

src/Controller/DebugController.php
src/Repository/CollectorRepository.php
src/Repository/CollectorRepositoryInterface.php

| Related to | https://github.com/yiisoft/yii-debug-frontend/pull/9

Remove redundant code

---

src/Repository/CollectorRepository.php

Reverse sort summary (from recently to oldest)

---

composer.json
config/web.php
src/Repository/CollectorRepository.php

| Fixed issues  | #19 
:warning: Related to yiisoft/yii-debug#79

Don't access to debug files directly, use storage read instead.

---

config/routes.php
src/Controller/DebugController.php
src/Repository/CollectorRepository.php
src/Repository/CollectorRepositoryInterface.php

Return object by id

---

config/routes.php
src/Provider/DebugApiProvider.php

Merge after https://github.com/yiisoft/router/pull/99

Apply new routes syntax

---

composer.json

Remove yiisoft/router-fastroute from composer.json

---

src/Middleware/ResponseDataWrapper.php

Remove @internal from middleware

---

config/routes.php

see https://github.com/yiisoft/validator/pull/134

Adopt to new yiisoft/validator

---

composer.json

Allow upper version for psr/container

---

src/Provider/DebugApiProvider.php

New providers

---

composer.json
config/routes.php
src/Controller/DebugController.php
src/Exception/NotFoundException.php
src/Provider/DebugApiProvider.php
src/Repository/CollectorRepository.php

Adjust routes, finalize classes, update dependencies

---

.github/workflows/build.yml
.github/workflows/mutation.yml
.github/workflows/static.yml
.scrutinizer.yml
composer.json
config/routes.php

Use yii-middleware package

---

src/Controller/DebugController.php

| Is bugfix?    | ✔️/❌
| Fixed issues  | 
:warning: Merge after https://github.com/yiisoft/router/pull/128

Adapt to router changes

---

config/routes.php
src/Controller/DebugController.php
src/Middleware/DebugHeaders.php

| Is bugfix?    | ✔️/❌
| Fixed issues  | https://github.com/yiisoft/yii-debug-viewer/issues/22

Change API endpoint

---

config/routes.php

Adapt to yii-middleware changes

---

composer.json
config/routes.php
src/Middleware/Cors.php

| Breaks BC?    | ✔️
| Fixed issues  | #47

Simple CORS middleware

---

src/Controller/DebugController.php
src/Controller/InspectController.php

Fix object serialization

---

src/Controller/DebugController.php
src/Controller/InspectController.php

Reverts yiisoft/yii-debug-api#50

Revert "Fix object serialization"

---

src/Controller/InspectController.php
src/Inspector/Command/PHPUnitCommand.php
src/Inspector/Command/PsalmCommand.php

Add psalm command

---

src/Controller/InspectController.php

Filter exceptions

---

.github/workflows/rector.yml
composer.json
rector.php
src/Controller/DebugController.php
src/Controller/InspectController.php
src/Inspector/Command/CodeceptionCommand.php
src/Inspector/Command/PHPUnitCommand.php
src/Inspector/Command/PsalmCommand.php
src/Inspector/Test/CodeceptionJSONReporter.php
src/Inspector/Test/PHPUnitJSONReporter.php
src/Middleware/DebugHeaders.php
src/Repository/CollectorRepository.php

Added rector/rector to CI and composer.json. Mass creation refers to https://github.com/yiisoft/yii-dev-tool/pull/232

Add rector [batch]

---

config/routes.php
src/Controller/InspectController.php

Now we can walk through the project and view a lot of file types and directories.
Such binary files as images, sqlite db and etc. are not supported for now.

Feature: File explorer

---

src/Controller/InspectController.php

Add ability to access file by absolute path

---

config/params.php
config/routes.php
src/Controller/InspectController.php
src/Inspector/Command/CodeceptionCommand.php
src/Inspector/Command/InspectorCommandInterface.php
src/Inspector/Command/PHPUnitCommand.php
src/Inspector/Command/PsalmCommand.php
src/Inspector/CommandInterface.php
src/Inspector/CommandResponse.php

Restructure commands and add ability to configure them

---

composer.json
config/routes.php
src/Controller/InspectController.php

| Depends on  | https://github.com/yiisoft/translator/pull/94

Add an ability to read and write translations

---

src/Inspector/Command/CodeceptionCommand.php
src/Inspector/Command/PHPUnitCommand.php
src/Inspector/Command/PsalmCommand.php
src/Inspector/CommandResponse.php
src/Inspector/Test/CodeceptionJSONReporter.php

Fix commands response

---

composer-require-checker.json
composer.json
config/params.php

Move dev dependencies to composer dev section

---

config/routes.php
src/Controller/InspectController.php

Here is the preview how it can look like

Add phpinfo action

---

composer.json
config/routes.php
src/Controller/GitController.php

Git inspections

---

config/routes.php
src/Controller/CommandController.php
src/Controller/InspectController.php
src/Inspector/Command/BashCommand.php

Now it's possible to run hooks and any multiple commands.
How it works in yii-dev-panel:

Add composer scripts support

---

src/Controller/InspectController.php

Fix class list to explore

---

src/Controller/InspectController.php
src/Middleware/ResponseDataWrapper.php

Exception collector adjustments

---

psalm.xml
src/Controller/InspectController.php
src/Inspector/Test/PHPUnitJSONReporter.php

Psalm level 4

---

src/Controller/CacheController.php
src/Controller/GitController.php
src/Controller/InspectController.php

Replace encoding/decoding with a dumper's feature #55

---

composer-require-checker.json
composer.json
config/routes.php
src/Controller/DebugController.php
src/Exception/PackageNotInstalledException.php
src/HtmlViewProviderInterface.php
src/ModuleFederationAssetBundle.php
src/ModuleFederationProviderInterface.php
src/ViewProviderInterface.php

SSR panels

---

src/Repository/CollectorRepository.php

Optimize reading

---

composer.json
config/routes.php
src/Controller/InspectController.php

Url checker

---

src/Controller/InspectController.php

| Fixed issues  | 
https://github.com/yiisoft/translator/blob/c24328a82e44629fc3fbe092e2e905df2c9045a8/src/Translator.php#L48-L59C6
https://github.com/yiisoft/translator/blob/c24328a82e44629fc3fbe092e2e905df2c9045a8/src/Translator.php#L115-L123

Merge translator message

---

src/Controller/ComposerController.php
src/Controller/GitController.php
src/Controller/InspectController.php
src/Inspector/Command/BashCommand.php

| Is bugfix?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Fix errors

---

.github/workflows/build.yml
composer-require-checker.json
composer.json
config/di-web.php
phpunit.xml.dist
src/Inspector/Database/Db/DbSchemaProvider.php
tests/Inspector/Database/DbSchemaProviderTest.php

Replace `AR` with `Db`.

---

config/params.php

Fix annotation-paths for yii-swagger in params.php

---

CHANGELOG.md
composer.json

Bump psr/http-message version to ^2.0

---

src/Debug/Middleware/DebugHeaders.php
tests/Unit/Debug/Middleware/DebugHeadersTest.php

Allow to use `DebugHeaders` without debugger
